### ISSUE TITLE
problem with markdown files

### ISSUE THREAD

**Issue by nvinayvarma189** [aimacode/aima-exercises#12]
There are many conflicts in hosting the github pages with `markdown` being in the repository. For ex: In `bayes-nets-exercises.md` there are many errors which result in build failing of github pages. I encountered these errors in the `bayes-nets-exercises.md` file and I don't know still how many files produce the same errors. I think Jupyter notebooks are way better than markdown files in case of hosting and also with keeping the exercises consitent. 
I agree with @norvig as he pointed the disadvantages of notebooks and I'm trying to search for an alternative too. For now I fixed the build errors caused by the markdown files and I will submit a PR soon.

**Comment by anandwana001** [comment]
If this issue solved can we close it?

**Comment by nvinayvarma189** [comment]
yeah @anandwana001. This can be closed. Thanks for reminding.
