### ISSUE TITLE
Requirements for aima-exercises [gsoc]

### ISSUE THREAD

**Issue by vishakha-lall** [aimacode/aima-exercises#17]
Hi!
I am aspiring to contribute to aima-exercises as a GSoC student. I would like to work on designing a format for exercises, where some solutions can be accessed only by professors, or based on criteria set by professors. The aima-gsoc page also talks about creating a community of volunteers to add new exercise questions and solutions, however, that would require dynamic content. Would that be hosted on Github Pages too? As I understand Github Pages works great only for static content.
I would appreciate any suggestions on where to start contributing.
Referring to [this issue](https://github.com/aimacode/aima-gsoc/issues/9) on aima-gsoc.

**Comment by heisenbuug** [comment]
@vishakha-lall Hey, even I came here for same. First go through gsoc page of aima and decide a project on which you can work. Then go through the issues and work that has already been done. Then start contributing.

**Comment by anandwana001** [comment]
Hi, I am looking forward to contributing to aima_exercise.

@vishakha-lall We can use *Firebase* for dynamic content. Platform for students and teachers to add new exercises to Firebase Database and we can also use other features of firebase like authentication and others.

@heisenbuug It seems like the first step of aima_exercise to convert all LaTeX into markdown has been done, only 27-AI-The-Present-And-Future is left. We can start with our second step *Design a good format to display the exercises as pretty GitHub pages.*

**Comment by vishakha-lall** [comment]
@anandwana001 since Github does not have any server support, dynamic content cannot be hosted. I suggest using angular js which runs on the client end, and can perform authentication and similar functionality.

**Comment by anandwana001** [comment]
@vishakha-lall can we start suggesting design ideas first so that mentors can confirm it and we can move forward accordingly!!

**Comment by vishakha-lall** [comment]
@anandwana001 I don't think I'm the best person to ask that to. You should probably contact the mentor. :)
