### ISSUE TITLE
Sample site [GSoC]

### ISSUE THREAD

**Issue by sdabhi23** [aimacode/aima-exercises#24]
Hey, I see I am very late to join the discussion.

I read all the conversations and issues being discussed over here and felt that using markdown. The next challenge was to separate the styling and  the contents of the exercise as suggested by @Nalinc. I would also readily agree with him as thsi would make the code more readable and maintainable.

I decided to go with dynamic rendering of markdown to html is our best bet. This will make it easier for the future contributors to add new pages and exercises. On of the reasons of not opting for Jeykll is that we can easily replace the html/css structure with something more modern like react.js

I loved the way @vishakha-lall implemented the comments section. Though I haven't added this to my demo site yet, this feature is super awesome!

And here's the link to the sample site: https://sdabhi23.github.io/aima-exercise-sample/

Are we ready to pay for a domain name and hosting or we will only use the one provided on github pages? Also if we can split the questions from the tex file and save them to the database (which I am very much sure is possible to implement using some simple python script), making the site interactive will become very much easier!!

We can get sufficient amount of free hosting at hasura, by using their free tier.

@norvig any thoughts on the above mentioned points?

**Comment by vishakha-lall** [comment]
@sdabhi23 Thank you for the appreciation. I went through your sample site too. It looks nice, although the Latex inline Math equations are not rendered properly. Can you correct that? People have mostly used MathJax in their samples, you might want to give that a shot.

**Comment by sdabhi23** [comment]
@vishakha-lall thanks for pointing that out. I have fixed it. Can you please confirm? Also I have added the 3rd chapter to demonstrate the inline equations are now being rendered properly.

**Comment by vishakha-lall** [comment]
@sdabhi23 It does not seem to be loading the equations correctly. I have attached the image for reference. 
![image](https://user-images.githubusercontent.com/31643223/37697958-20026f10-2d06-11e8-984e-631620f97a09.png)
Notice E$x$ ...

**Comment by sdabhi23** [comment]
It's working nicely on localhost 😞 
![image](https://user-images.githubusercontent.com/25759344/37698123-0f3cd160-2d07-11e8-9ade-eeb3f7c5fb8b.png)

**Comment by vishakha-lall** [comment]
Clearly, there seems to be some issue when you are hosting it on Github pages, do you see some errors in the console?

**Comment by sdabhi23** [comment]
Looks like Github takes sometime to update the pages after the repo is updated. Here's a screenshot for  your reference. Check again please 😅 

![image](https://user-images.githubusercontent.com/25759344/37698355-866d4872-2d08-11e8-8098-cf3e11d2a857.png)

**Comment by vishakha-lall** [comment]
Yes, it looks fine now.

**Comment by Nalinc** [comment]
@sdabhi23 
> Are we ready to pay for a domain name and hosting or we will only use the one provided on Github pages? 

Paying for a domain name seems unlikely and no decision has been made on the hosting space yet. A lot of people have explored Github pages, but we might as well consider Kaggle to host the exercises. See #21 

> Also if we can split the questions from the tex file and save them to the database (which I am very much sure is possible to implement using some simple python script), making the site interactive will become very much easier!!

We already have extracted questions from LaTeX to Markdown files. Storing the same questions in a  database will not only make things redundant but also make it difficult for instructors to add new questions. Further, who will administer the database? How will new questions be added? By database, do you mean a relational database or NoSQL? In either case, do you have a specific schema in mind?

I like your sample exercise, but hasn't the idea of using a custom markdown parser already been explored in #23 ?

**Comment by vishakha-lall** [comment]
@sdabhi23 I agree with @Nalinc, the idea of storing exercises in a database would be redundant and kill the purpose of authors modifying exercises conveniently.

**Comment by sdabhi23** [comment]
@Nalinc I am thinking of a NoSQL database, Postgres to be more specific.

For adding solutions to existing questions and newer questions I have thought of a portal, which will also help secure the input of new questions. This will also help us track the upvotes/downvotes for a specific questions. Also we can even hide solutions to particular questions as mentioned in the project description on [aima-gsoc](https://github.com/aimacode/aima-gsoc/blob/master/README.md#project-4-initiate-aima-exercises).

All I mean to say is that all the major functionalities required can be very easily implemented if we have a database. I will be happy volunteer for administering the database even after the end of GSoC, until we have a large enough community of contributors and someone else also volunteers to share this responsibility.

I don't have a specific schema as of yet, but then isn't the GSoC coding period intended for working on the same? :grinning:

**Comment by Nalinc** [comment]
@sdabhi23 Postgres is **not** a NoSQL database! 

If you decide to go with Postgres anyway, I would recommend you to mention the schema in your proposal. Even if you plan to use a NoSQL database, you should mention the document structure and collection type. GSoC coding period is meant for coding the things you propose in your application. Also, you are more likely to miss the phase one evaluation during GSoC if you have less time for actual coding. :)

**Comment by sdabhi23** [comment]
@Nalinc sorry. My bad. I just got confused regarding Postgres. And yes, I still plan on using Postgres.

A few questions:

* Can a exercise have multiple solutions?
* Do all the solutions of a particular exercise  need to be shown on the site?

**Comment by Nalinc** [comment]
Hi @sdabhi23 
> "Can an exercise have multiple solutions?"

I would say yes, some exercises can have multiple solutions depending on how you treat the problem

> "Do all the solutions of a particular exercise need to be shown on the site?"

I don't think so. @norvig said instructors should be able to give few exercises as homework to the students. In that case, we don't want to show all the solutions on the site

**Comment by Nalinc** [comment]
@sdabhi23  Also, I appreciate your work on sample exercises, but now we are planning to pivot around Kaggle to see possibilities of using it to host aima-exercises. 
Closing this issue, but would love to get your feedback on https://github.com/aimacode/aima-exercises/issues/21
