### ISSUE TITLE
Conversion from LaTeX to Markdown

### ISSUE THREAD

**Issue by ansh103** [aimacode/aima-exercises#3]
First of all, I want to introduce the relevant details:
1) It can be done using [Pandoc](http://pandoc.org/demos.html) 

2) There are some problems associated with Pandoc. It's ignoring few of the important things:-
    a) Bold or Italics
![1](https://user-images.githubusercontent.com/31566246/36144518-46d7ad06-10d4-11e8-9df8-a4eeb663ea95.png)

    b) What to do about the headings? The questions numbers can either be replaced by "a new line" indicating question changed or we can have question numbers. Considering this all will go online, there is no need of putting 11.3 or 11.4. Or is there?

3) Also, there is this extra info about each question coming up? Should the code be modified to ignore [conformant-flip-exercise] in above image altogether or is it required to be there in Markdown? 

4) Then the part regarding images. Should the images be imported from images folder while conversion from LaTeX to Markdown or it should be linked to be used in the aima-exercises page. (to be made later on)

5) Finally, whether to use Pandoc or not? Is there a need for different code all together for aima-exercises or should we continue tweaking Pandoc settings?

**Comment by Sayan98** [comment]
Hey @ansh103, just out curiosity, have you tried running `pdflatex` on the latex files? I seemingly can't get them to compile all right. It is probably due to improper incorporation of the `.sty` file. 

Here's a screengrab showing the output of the `pdflatex` command on `robotics-exercises.tex`: 
<img width="682" alt="screen shot 2018-02-14 at 4 46 14 pm" src="https://user-images.githubusercontent.com/8839504/36201638-9baeec54-11a6-11e8-92bd-1619651722f7.png">

**Comment by ansh103** [comment]
There are issues regarding \begin{exercise} and \end{exercise}. @norvig  had mentioned about them in the Readme file. But what concerns me more is that styling as a whole is not working as expected. So you are right on that.  Because I tried the same after taking care of \begin{exercise}.

**Comment by Sayan98** [comment]
You're correct. The macros are defined in [`aima3e.sty`](https://github.com/aimacode/aima-exercises/blob/master/latex/aima3e.sty). Adding that to the path (for TeX) should've solved the problem. It didn't.

>  Because I tried the same after taking care of \begin{exercise}.

Could you elaborate on this?

**Comment by ansh103** [comment]
@Sayan98 I did try it. No luck in getting it through. Did you make any progress?

**Comment by Sayan98** [comment]
Negative.

**Comment by sambitdash** [comment]
I just used a script to convert all the files to Markdown. You can see the files at:
[https://github.com/sambitdash/aima-exercises/tree/master/md](https://github.com/sambitdash/aima-exercises/tree/master/md)
If you think it will help to use these as a starting point I can submit a pull request.

**Comment by heisenbuug** [comment]
I am trying to run these latex files on atom but I am getting errors...was anyone able to rub those files?

**Comment by norvig** [comment]
Let's continue this in Issue #5
