### ISSUE TITLE
Inconsistencies found in Jupyter notebook files

### ISSUE THREAD

**Issue by sachin10101998** [aimacode/aima-exercises#51]
I was going through the codebase and found that there are lots of inconsistencies in jupyter notebook files. 
1) All the chapters haven't been indexed. 
2) I don't know what process was used to produce the jupyter files because there are quite a lot of inconsistencies.  Chapter 2 has two jupyter files and in one of them, the first exercise has been written as if it was an introduction and the second exercise has been marked as the first exercise. I am adding the screengrab here of the same. The exercise 2.1 in below figure is actually 2.2, 2.2 is actually 2.3 and so on. However, the second file is correctly coded.
![Screenshot (290)](https://user-images.githubusercontent.com/34926285/54488077-48e06980-48c3-11e9-8ba5-35119a85a3cd.png)
Same is the case with chapter 11. In the alter files the questions have not been indexed. I figured out that there are figures given in one of the files. But I fail to understand the importance of two different files. Please help me out here. 
I found a few other inconsistencies too. I'd work on resolving these issues and send a pull request soon.

**Comment by Nalinc** [comment]
We're not using Jupyter Notebooks anymore
