### ISSUE TITLE
Include bibliography file

### ISSUE THREAD

**Issue by Nalinc** [aimacode/aima-exercises#7]
Some exercises are citing papers and external references. To generate meaningful results, it is important that we include the bibliography file while compiling the LaTex files.

Following is an example exercise from `search-exercises.tex`.
>
> We gave two simple heuristics for the 8-puzzle: Manhattan distance and misplaced tiles.  
> Several heuristics in the literature purport to improve on this---see, for example, 
> **\citeA{Nilsson:1971}, \citeA{Mostow+Prieditis:1989}, and \citeA{Hansson+al:1992}.** 
> Test these claims by implementing the heuristics and comparing the performance 
> of the resulting algorithms.

Based on this, we might also need to decide how to handle bibliographic information and which format to choose while displaying the references.

**Comment by norvig** [comment]
This is a good point, but there's not that many references  (`grep cite *exercises.tex | wc` says 35 lines), so we can probably handle them by hand.
